import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
weight_dtype = torch.float16 if device.type == "cuda" else torch.float32

DEFAULT_STYLE_SIZE = 768
DEFAULT_OUTPUT_SIZE = 1024
DEFAULT_STYLE_SCALE = 0.8
DEFAULT_GUIDANCE_SCALE = 7.5
DEFAULT_NUM_INFERENCE_STEPS = 50
MIN_GUIDANCE_SCALE = 5.0
DEFAULT_LATENT_CHANNELS = 4
VAE_DOWNSCALE_FACTOR = 8
EPSILON = 1e-6

COLOR_STD_NORMALIZER = 50.0
TEXTURE_VAR_NORMALIZER = 1000.0
EDGE_THRESHOLD_LOW = 50
EDGE_THRESHOLD_HIGH = 150
WEAK_STYLE_THRESHOLD = 0.4
STRONG_STYLE_THRESHOLD = 0.7

DEFAULT_CONTRAST_FACTOR = 1.2
DEFAULT_SATURATION_BOOST = 1.1
DEFAULT_POST_PROCESS_STRENGTH = 0.3
TEXTURE_BLEND_WEIGHT = 0.08
COLOR_BLEND_WEIGHT = 0.92

AUTO_OPT_STYLE_DELTA = 0.35
AUTO_OPT_GUIDANCE_DELTA = 3.0
AUTO_OPT_STEPS_DELTA = 40

MAX_IMAGE_FILE_SIZE_MB = 50
MAX_IMAGE_DIMENSION = 4096
MAX_STYLE_REFERENCES = 5
MAX_SIMULTANEOUS_TECHNIQUES = 3

SCHEDULE_EARLY_PHASE = 0.3
SCHEDULE_MIDDLE_PHASE = 0.7
EARLY_STYLE_BOOST = 1.15
LATE_STYLE_REDUCTION = 0.8

SEMANTIC_ATTENTION_THRESHOLD = 0.5
SEMANTIC_STYLE_BACKGROUND = 1.0
SEMANTIC_STYLE_FOREGROUND = 0.85
ATTENTION_BLUR_KERNEL = 15

COLOR_TRANSFER_MODES = ["reinhard", "linear", "mkl"]

FDSM_LOW_FREQ_CUTOFF = 0.3
FDSM_HIGH_FREQ_START = 0.7
FDSM_STRUCTURE_WEIGHT = 1.0
FDSM_TEXTURE_WEIGHT = 0.5
FDSM_TRANSITION_SMOOTH = 0.15
MULTISCALE_WEIGHTS = {
    512: 0.25,
    768: 0.35,
    1024: 0.40,
}

SAF_WAVELET_TYPE = "db4"
SAF_DECOMP_LEVELS = 3
SAF_COARSE_WEIGHT = 0.8
SAF_DETAIL_WEIGHTS = [0.4, 0.5, 0.6]
SAF_FUSION_ALPHA = 0.5

PLR_NUM_STAGES = 3
PLR_RESOLUTION_RATIOS = [0.5, 0.75, 1.0]
PLR_REFINEMENT_WEIGHTS = [0.15, 0.25, 0.35]
PLR_INTERPOLATION_MODE = "bicubic"

HCP_HARMONIC_ORDER = 3
HCP_PROTECTION_RADIUS = 0.3
HCP_ATTENUATION_FACTOR = 0.08
HCP_SMOOTH_KERNEL = 7
